name: my_anime_list
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  http: 0.13.5
  youtube_player_flutter: 8.1.0
  convex_bottom_bar: 3.0.0
  loading_animation_widget: 1.2.0+2
  pull_to_refresh: 2.0.0
  sizer: 2.0.15
  carousel_slider: 4.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

